### PR TITLE
Updated for 1.0.2 and added symmetry updates

### PR DESCRIPTION
**Pull request by Angel-125**
This change updates CrossFeedEnabler to 1.0.2 and accounts for symmetry parts.

### CODE REVIEW

**Comment by NathanKell** [comment]
Sorry, this now conflicts with @Gerry1135 's PR which I merged. I'm happy to merge this in once you deconflict it...

**Comment by NathanKell** [comment]
@Angel-125  should I try to merge this manually, or can you fix it on your end?

**Comment by Angel-125** [comment]
I'll fix the merge conflicts, no problem.

**Comment by Angel-125** [comment]
Ok, see if that helps. :)

**Pull request merged**
