### PR TITLE
Fixed exception in VAB with Nose cones

### PR DESCRIPTION
**Pull request by sswelm**
crossfeed does not need to function in the VAB, but it does cause problem when updated in the VAB

### CODE REVIEW

**Comment by NathanKell** [comment]
Ah, but it _does_ need to function in the editor, as otherwise MJ and KER (and anything else) won't give correct delta V stats. Yes, I'm aware that the Engineer Report doesn't know what to do with it, but merely disabling it is not a solution.

**Comment by sswelm** [comment]
Then we need to detect somehow that it should no apply when it is not necessary, like when it is connected stack. because it would already flow anyway

**Comment by NathanKell** [comment]
Yes. The case of adding one's parent to one's own flow table can be removed. It's when one adds oneself to one's own parent that it needs to crossfeed.

**Comment by sswelm** [comment]
Not sure how to implement that, you better implement it yourself

**Comment by Gerry1135** [comment]
It may need to look through the Part.attachNodes list for the one that attaches to the parent part and read the nodeType from that.

**Comment by NathanKell** [comment]
Yep. I recreated the stock flow code in RF, so I can use that basis.

**Pull request closed without merging**
